#spring.application.name=demo


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/your_database_name
    username: your_username
    password: your_password
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # (??: create, update, validate, none)
    show-sql: true  # ???? SQL ?? ?? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect  # MariaDB? ?? ?? ??
